# Generated by Django 4.2 on 2023-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, null=True, to='api.movie'),
        ),
    ]
