# Generated by Django 4.0.7 on 2023-04-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_imdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='recommended',
        ),
        migrations.DeleteModel(
            name='FavoritedMovie',
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
