# Generated by Django 4.2 on 2023-04-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_recommended_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, to='api.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='streaminfo',
            field=models.ManyToManyField(blank=True, to='api.streaminfo'),
        ),
    ]
