# Generated by Django 4.0.7 on 2023-04-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
